/** 包根入口：re-export 预置插件清单 */
export { default as demoPlugin } from './demo/index'
export { default as marketPlugin } from './market/index'
export { useMarketStore } from './market/store'
export { connectionPlugin } from './connection/index'
export { modelsPlugin } from './models/index'
export { connectorsPlugin } from './connectors/index'
export { skillsPlugin } from './skills/index'
export { agentsPlugin } from './agents/index'
export { phonePairPlugin } from './phone-pair/index'
export { shellChromePlugin } from './shell-chrome/index'
export { chatflowPlugin } from './chatflow/index'
export { explorerPlugin } from './explorer/index'
export { markdownPlugin } from './markdown/index'
export { codeEditorPlugin } from './codeeditor/index'
export { imageViewerPlugin } from './image-viewer/index'
export { docPreviewPlugin } from './docpreview/index'
export { webViewerPlugin } from './web-viewer/index'
export { videoViewerPlugin } from './video-viewer/index'
export { svgboardPlugin } from './svgboard/index'
export { dashboardPlugin } from './dashboard/index'
